scrapper:
  timeout: 30
  retries: 3
  delay : 2
  url: "https://www.screener.in/company/RELIANCE/consolidated/" 
  section_id:
    quarter: "quarters"
    profit&loss: "profit-loss"
    balance_sheet: "balance-sheet"
    cash_flow: "cash-flow"
    ratios : "ratios"

path:
  data_dir: data
  raw_data: raw
  processed_data: processed
  dashboard_dir: dashboard
  dashboard_data: data